#!/usr/bin/env bash
# nohup \
#     /usr/bin/time --verbose \
#     ./pipe >| \
#     sm.out 2>| \
#     sm.err &

TAXID="1423"
TAXID_refseq="${TAXID}_refseq.tsv"
OUT="genomes.txt"

CACHE=~/.local/snakemake


function generate_ingenomes
{
    utils/get_taxid_refseq.R "$TAXID"
    cut -f1 -d$'\t' "$TAXID_refseq" | sed '1d' >| "$OUT"
}


function run_snakemake
{
    mkdir -p "$CACHE"
    export SNAKEMAKE_OUTPUT_CACHE="$CACHE"
    snakemake --cores all --cache -np
}


function main
{
    generate_ingenomes
    run_snakemake
}


main
