#!/usr/bin/env bash

# nohup \
#     /usr/bin/time --verbose \
#     ./pipe dry 1423 >| \
#     sm.out 2>| \
#     sm.err &


DRY="$1" # Only the word "run" works, any other one, triggers dry-run
TAXID="$2" # e.g. bsub "1423"

# Snakemake prerequisites
OUT="genomes.txt"
CACHE=~/.local/snakemake


function generate_ingenomes #TAXID
{
    TAXID="$1"
    utils/get_taxid_refseq.R "$TAXID"
    cut -f1 -d$'\t' "${TAXID}_refseq" | sed '1d' >| "$OUT"
}


function run_snakemake # DRY
{
    DRY="$1"
    mkdir -p "$CACHE"
    export SNAKEMAKE_OUTPUT_CACHE="$CACHE"
    if [[ "$DRY" != "run" ]]
    then
        snakemake --cores all --cache -np
    else
        snakemake --cores all --cache
    fi
}


function main # DRY TAXID
{
    DRY="$1"
    TAXID="$2"
    generate_ingenomes "$TAXID"
    run_snakemake "$DRY"
}


main "$DRY" "$TAXID"
