#!/usr/bin/env bash
# feed the word "run" into "$1" to get real the deal

# nohup \
#     /usr/bin/time --verbose \
#     ./pipe >| \
#     sm.out 2>| \
#     sm.err &

TAXID="1423"
TAXID_refseq="${TAXID}_refseq.tsv"
OUT="genomes.txt"

CACHE=~/.local/snakemake


function generate_ingenomes
{
    utils/get_taxid_refseq.R "$TAXID"
    cut -f1 -d$'\t' "$TAXID_refseq" | sed '1d' >| "$OUT"
}


function run_snakemake
{
    mkdir -p "$CACHE"
    export SNAKEMAKE_OUTPUT_CACHE="$CACHE"
    if [[ "$1" != "run" ]]
    then
        snakemake --cores all --cache -np
    else
        snakemake --cores all --cache
    fi
}


function main
{
    generate_ingenomes
    run_snakemake "$1"
}


main "$1"
